### ISSUE TITLE
Cleanup the KEY parameter from the docker compose files as it can cause confusion

### ISSUE THREAD

**Issue by mandaeduard** [zuavra/nginx-ip-whitelister#20]
Hi,

Thank you for developing this project! I've started using it today and I've had some issues because I tried to use the same key that I set in the docker compose file. I've reread the documentation a couple of times until I've seen that that is not allowed anymore and instead I should use the nginx headers. 

Could you adjust the docker compose files?

**Comment by mandaeduard** [comment]
The same applies for the FIXED_TIMEOUT parameter

**Comment by zuavra** [comment]
Of course. Fixed with [e5333b5](https://github.com/zuavra/nginx-ip-whitelister/commit/e5333b53a01864c0e0359b40fac0b84a54629393) on master branch.
